name: Bug Report
description: Report something that's broken.
body:
  - type: input
    attributes:
      label: Description
      description: Provide a detailed description of the issue you are facing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Provide detailed steps to reproduce your issue.
    validations:
      required: true
