  name: Documentation Issue
  description: Fix documentation.
  body:
    - type: input
      attributes:
        label: Fix file
        description: Specify the path to the file to be fixed.
      validations:
        required: true
