  name: Feature Request
  description: Suggest some feature.
  body:
    - type: textarea
      attributes:
        label: Detail
        description: Describe the feature detail.
      validations:
        required: true
